Add download user list button
SmartcitySantiagoChile/fondefVizServer pull request #104
Opened 2021-08-23 23:13 UTC by Bastianleaf

Se agrega botón de descarga de lista de usuarios con su información y permisos asociados (grupos asociados)

2021-08-26 01:47 UTC, felipinbombin requested changes

2021-08-26 01:47 UTC, felipinbombin commented on localinfo/urls.py
> +    url(r'^downloadUserData/$', DownloadUserList.as_view(), name='downloaduserlist')
estás dos urls deben tener aplicado `login_required`, sin esto son urls públicas que cualquier persona puede acceder. Esto también se debería aplicar a la url `faq`.

2021-08-26 20:04 UTC, Bastianleaf commented on localinfo/urls.py
> +    url(r'^downloadUserData/$', DownloadUserList.as_view(), name='downloaduserlist')
Corregido

2021-08-26 21:33 UTC, Bastianleaf commented
Se agregan las mejoras solicitadas.

2021-08-27 19:58 UTC, felipinbombin approved these changes

2021-08-27 20:07 UTC, merged