Delete past results on empty query
SmartcitySantiagoChile/fondefVizServer pull request #105
Opened 2021-08-31 19:41 UTC by Bastianleaf

Se modifican los archivos js para eliminar resultados cuando la query no entrega resultados.
La solución general para la mayoría de los archivos es cambiar la lógica del aftercall. Si no se ejecuta la función processData, se ejecuta el método clearDataDisplay que se encarga de vacíar los charts, tablas y otros elementos.

Para los mapas la solución es ejecutar processData con datos vacíos, esto automaticamente limpia el mapa.

2021-08-31 23:22 UTC, Bastianleaf commented
Se corrigen los tests.

2021-09-01 03:50 UTC, felipinbombin requested changes
La vista "speed/ranking" no se limpia cuando la consulta no entrega datos.

La vista profile/trajectory/ (Perfil de carga -> trayectoria) tira un error y no se muestra la visualización. Me parece que estaba de antes este bug.
![image](https://user-images.githubusercontent.com/2617940/131607986-a314ca5d-5579-4f3e-974a-b0373c7dcba6.png)

2021-09-01 20:34 UTC, Bastianleaf commented
> La vista "speed/ranking" no se limpia cuando la consulta no entrega datos.
> 
> La vista profile/trajectory/ (Perfil de carga -> trayectoria) tira un error y no se muestra la visualización. Me parece que estaba de antes este bug.
> ![image](https://user-images.githubusercontent.com/2617940/131607986-a314ca5d-5579-4f3e-974a-b0373c7dcba6.png)

Corregidos ambos casos.

2021-09-02 06:13 UTC, felipinbombin approved these changes

2021-09-04 02:51 UTC, merged