Feature/add evasion permission
SmartcitySantiagoChile/fondefVizServer pull request #109
Opened 2021-09-15 14:19 UTC by Bastianleaf

# Cambios en Backend
## Permisos
- Se agrega permiso de evasión en clase **PermissionBuilder** de _localinfo/helper.py_
- Se agrega método estático **has_evasion_permission** a la clase **PermissionBuilder**, esto verifica la existencia del permiso para un usario dado.

## Consultas sin evasión
- Se añade el parámetro _show_evasion_ a las clase **get_base_profile_by_expedition_data_query**. Solo consulta por los datos de evasión en caso de que _show_evasion_ sea verdadero.
- Se añade el parámetro _show_evasion_ a la clase  **get_profile_by_expedition_data**. Solo agrega métricas de evasión al bucket en caso de que _show_evasion_ sea verdadero.
 - Se agregan los test correspondientes

## Vista de Perfil de Carga (clase **LoadProfileByExpeditionData**)
- Se agrega consulta de permiso de ver datos evasión para el usuario que haga llamada a la vista. La respuesta se utiliza para las consultas, para el método **transform_answer**,  para definir cuál clase de exportación se usa en caso de exportar datos y se agrega la respuesta JSON hacia el frontend.
- Se modifica el método **transform_answer** añadiendo el parámetro _show_evasion_. Se separan los componentes de los datos transformados, los datos asociados a evasión se añaden solo en caso de que _show_evasion_ sea verdadero.
- Se corrigen tests.

## Exportar datos
- Se añade nueva clase **ProfileWithoutEvasionCSVHelper** a _csvhelper/helper.py_ para crear un csv sin datos de evasión al momento de exportar datos.
- Se a ñade nueva clase **ProfileByExpeditionWithoutEvasionData** a _csvhelper/profile.py_ para manejar la exportación de datos sin evasión.
- Se agrega la referencia a la nueva clase en _dataDownloader/downloadData.py_ y _datamanager/helper.py_

# Cambios en Frontend
## profile/views.py
- Se añade el estilo _display: none_ a la tabla de estadísticas globales del template. Esto es para que la tabla sea distinta en caso de que se pueda o no ver los datos de evasión
## byExpedition.js
- Se agrega método **manageEvasionDisplay** encargado de ocultar las visualizaciones que muestren información de evasión.
- Se utiliza la variable **showEvasionData** obtenida desde el backend para usar el método **manageEvasionDisplay**  y cambiar los datos inexistentes a 0 en la visualización. Esto último tiene fin de no cambiar la estructura de la solución anterior.

2021-09-16 17:53 UTC, felipinbombin requested changes

2021-09-16 17:53 UTC, felipinbombin commented on localinfo/helper.py
> +        return user.groups.filter(name='Ver datos de evasión en perfil de carga').exists()
Falta agregar el permiso en el método `create_permission_based_on_operators`, no aparece en la lista de permisos disponibles

2021-09-16 17:53 UTC, felipinbombin commented on dataDownloader/csvhelper/helper.py
> +        print(formatted_row)
quitar print

2021-09-16 17:53 UTC, felipinbombin commented on esapi/tests/testProfileIndex.py
> +        print(result.to_dict())
quitar print

2021-09-16 18:11 UTC, Bastianleaf commented on esapi/tests/testProfileIndex.py
> +        print(result.to_dict())
Ok

2021-09-16 18:11 UTC, Bastianleaf commented on dataDownloader/csvhelper/helper.py
> +        print(formatted_row)
Ok

2021-09-16 18:12 UTC, Bastianleaf commented on localinfo/helper.py
> +        return user.groups.filter(name='Ver datos de evasión en perfil de carga').exists()
Ok, voy a revisar porque si lo agregué.

2021-09-16 18:38 UTC, Bastianleaf commented
Comentarios corregidos

2021-09-20 16:14 UTC, felipinbombin approved these changes

2021-09-20 16:24 UTC, merged