Se actualizan js para evitar animación de carga cuando no se recibe i…
SmartcitySantiagoChile/fondefVizServer pull request #15
Opened 2020-02-06 20:04 UTC by Bastianleaf

…nformación.

2020-02-06 21:16 UTC, felipinbombin requested changes

2020-02-06 21:16 UTC, felipinbombin commented on bip/static/bip/js/byOperator.js
>              }
pienso que esto se debería quitar también, ya no es necesario

2020-02-06 21:16 UTC, felipinbombin commented on globalstat/static/globalstat/js/detail.js
>              }
pienso que esto se debería quitar también, ya no es necesario

2020-02-06 21:16 UTC, felipinbombin commented on globalstat/static/globalstat/js/resume.js
>              }
pienso que esto se debería quitar también, ya no es necesario

2020-02-06 21:16 UTC, felipinbombin commented on profile/static/profile/js/byExpedition.js
> +            hideLoading: hideLoading
¿dónde está definido esto? no se usa la variable `hideLoading` en el archivo filterManager.js, no debe ser necesario, por lo que la línea 805 tampoco a mi parecer

2020-02-07 12:17 UTC, Bastianleaf commented on bip/static/bip/js/byOperator.js
>              }
Ok

2020-02-07 12:17 UTC, Bastianleaf commented on globalstat/static/globalstat/js/detail.js
>              }
Ok

2020-02-07 12:17 UTC, Bastianleaf commented on globalstat/static/globalstat/js/resume.js
>              }
Ok

2020-02-07 12:18 UTC, Bastianleaf commented on profile/static/profile/js/byExpedition.js
> +            hideLoading: hideLoading
Es una variable que olvidé eliminar, lo haré.

2020-02-07 12:24 UTC, felipinbombin commented on profile/static/profile/js/byExpedition.js
> +            hideLoading: hideLoading
ok

2020-02-07 12:50 UTC, felipinbombin approved these changes

2020-02-07 12:50 UTC, merged