Feature/fix by stop view
SmartcitySantiagoChile/fondefVizServer pull request #21
Opened 2020-03-02 13:27 UTC by Bastianleaf

2020-03-02 14:33 UTC, felipinbombin commented on esapi/static/js/filterManager.js
> -    if ($STOP_FILTER.length) {
¿por qué ya no es necesario el if?

2020-03-02 14:52 UTC, Bastianleaf commented on esapi/static/js/filterManager.js
> -    if ($STOP_FILTER.length) {
Esto fue un error al estar modificando el código. Lo volveré a agregar.

2020-03-02 20:18 UTC, felipinbombin commented on esapi/static/js/filterManager.js
> -    if ($STOP_FILTER.length) {
ok, está pendiente

2020-03-03 12:41 UTC, Bastianleaf commented on esapi/static/js/filterManager.js
> -    if ($STOP_FILTER.length) {
Listo.

2020-03-03 16:13 UTC, felipinbombin requested changes

2020-03-03 16:13 UTC, felipinbombin commented on esapi/static/js/filterManager.js
> +    }
está duplicado este código con las líneas superiores ¿por qué?

2020-03-03 16:13 UTC, felipinbombin commented on esapi/static/js/filterManager.js
> +
esto debería ir dentro del `if ($STOP_FILTER.length) { ... }`

2020-03-04 13:16 UTC, Bastianleaf commented on esapi/static/js/filterManager.js
> +
Ok

2020-03-04 13:17 UTC, Bastianleaf commented on esapi/static/js/filterManager.js
> +    }
Lo eliminaré, debe haber sido algún error de copiar y pegar.

2020-03-04 13:21 UTC, Bastianleaf commented on esapi/static/js/filterManager.js
> +
Me retracto, si el código va dentro del if, no se carga el paradero guardado en localstorage. Es necesario que se ejecute inmediatamente al cargar la página.

2020-03-05 17:15 UTC, felipinbombin commented on esapi/static/js/filterManager.js
> +
ok

2020-03-05 17:15 UTC, felipinbombin approved these changes

2020-03-05 17:15 UTC, merged