Feature/speed matrix info
SmartcitySantiagoChile/fondefVizServer pull request #26
Opened 2020-03-04 13:23 UTC by Bastianleaf

2020-03-05 16:34 UTC, felipinbombin requested changes

2020-03-05 16:34 UTC, felipinbombin commented on templates/help/modal/filters/speed_map.html
> +      distancias recorridas en el tramo dividido por el tiempo promedio recorrido en este.</dd>
Corrección: `... . Esto se calcula como la suma de las distancias recorridas por todas las observaciones del tramo dividido por la suma de los tiempos recorridos por todas las observaciones del tramo`

2020-03-05 16:34 UTC, felipinbombin commented on templates/help/modal/filters/speed_map_by_section.html
> +    Esta se calcula como la distancia promedio recorrida entre el tramo inicial y final dividido en el tiempo promedio recorrido entre ambos tramos.</dd>
de nuevo, no es el promedio de los tiempos o distancias, sino que la suma de todas las distancias de todas las observaciones de todos los tramos dividida por la suma de todos los tiempos de todas las observaciones de todos los tramos considerados

2020-03-06 12:32 UTC, Bastianleaf commented on templates/help/modal/filters/speed_map.html
> +      distancias recorridas en el tramo dividido por el tiempo promedio recorrido en este.</dd>
Ok

2020-03-06 12:32 UTC, Bastianleaf commented on templates/help/modal/filters/speed_map_by_section.html
> +    Esta se calcula como la distancia promedio recorrida entre el tramo inicial y final dividido en el tiempo promedio recorrido entre ambos tramos.</dd>
Ok

2020-03-06 13:54 UTC, felipinbombin approved these changes

2020-03-06 13:54 UTC, merged