Feature/test
SmartcitySantiagoChile/fondefVizServer pull request #29
Opened 2020-03-18 12:37 UTC by Bastianleaf

2020-03-24 18:47 UTC, felipinbombin requested changes

2020-03-24 18:47 UTC, felipinbombin commented on bip/tests.py
>  # Create your tests here.
quitar este comentario

2020-03-24 18:47 UTC, felipinbombin commented on esapi/errors.py
> +        super(ESQueryDateRangeParametersDoesNotExist, self).__init__(403, message)
¿por qué se cambió este valor a 403? la idea de tener el 402 es asimilar el valor del error asociado a la no existencia de valor en alguna variable

2020-03-24 18:47 UTC, felipinbombin commented on esapi/helper/basehelper.py
> +        # create query to get unique list of values from field
el caracter '#' está asociado a comentarios dentro del código, en este caso el string corresponde a una descripción del método por lo que debe ir con '""" """'

2020-03-24 18:47 UTC, felipinbombin commented on esapi/helper/shape.py
> +            print(point_list)
esto hay que quitarlo

2020-03-24 18:47 UTC, felipinbombin commented on esapi/views/resume.py
> +            print(hit_row)
quitar print

2020-03-24 18:47 UTC, felipinbombin commented on esapi/views/resume.py
> +            print row
quitar print

2020-03-24 18:47 UTC, felipinbombin commented on esapi/views/resume.py
> +                    print(keys[key])
quitar print

2020-03-24 18:47 UTC, felipinbombin commented on esapi/views/resume.py
>          return JsonResponse(response)
pienso que falta ordenar el código (ctrl+alt+L) porque siempre se deja una línea en blanco al final

2020-03-24 18:47 UTC, felipinbombin commented on esapi/tests/testBaseIndex.py
>  class IndexNameTest(TestCase):
Los test de esta clase pueden ser reducidos en código haciendo lo siguiente:
- creando el método `def setUp(self)` y creando el mock en su cuerpo, así
```
patcher = mock.patch('esapi.helper.basehelper.settings')
self.addCleanup(patcher.stop)
mock_instance = patcher.start()
mock_instance.ES_CLIENT.return_value = None
```
Ahora esto será aplicado a cada test de la clase y por lo tanto podemos quitar el código repetido en cada uno de ellos. Referencia: https://docs.python.org/3.5/library/unittest.mock-examples.html#applying-the-same-patch-to-every-test-method (es válido para python 2.7)
- Otra alternativa es realizar lo que hace la clase de abajo, definir el mock como un decorador de la clase, esto evita crear el método ``setUp`. Así
```
@override_settings(ES_CLIENT=mock.MagicMock(return_value=None))
class IndexNameTest(TestCase)
```
esto es muuuucho más reducido y se debería lograr el mismo efecto

2020-03-24 18:47 UTC, felipinbombin commented on esapi/tests/testBaseIndex.py
> +        print(result)
quitar print

2020-03-24 18:47 UTC, felipinbombin commented on esapi/views/resume.py
> +        'name': 'N° de validaciones en décimo paradero de bus con más validaciones', 'chartName': '', 'order': 97},
deshacer las modificaciones a las líneas que definen los diccionarios, por temas de comprensión es mejor tenerlas como estaban a pesar de que pasen el ancho permitido

2020-03-24 18:47 UTC, felipinbombin commented on esapi/tests/testShapeView.py
> +        # self.assertDictEqual(answer, ESQueryRouteParameterDoesNotExist().get_status_response())
quitar si no se usa

2020-03-24 18:47 UTC, felipinbombin commented on esapi/tests/testShapeView.py
> +        # self.assertDictEqual(answer, ESQueryDateParametersDoesNotExist().get_status_response())
quitar si no se usa

2020-03-24 18:47 UTC, felipinbombin commented on esapi/tests/testResumeView.py
> +        # self.assertJSONEqual(response.content, expected)
quitar si no se usa

2020-03-24 18:47 UTC, felipinbombin commented on esapi/tests/testProfileView.py
> +    #     self.assertJSONEqual(response.content, expected)
quitar si no se usa

2020-03-25 12:58 UTC, Bastianleaf commented on bip/tests.py
>  # Create your tests here.
Ok

2020-03-25 12:59 UTC, Bastianleaf commented on esapi/helper/basehelper.py
> +        # create query to get unique list of values from field
Ok

2020-03-25 12:59 UTC, Bastianleaf commented on esapi/helper/shape.py
> +            print(point_list)
Ok

2020-03-25 12:59 UTC, Bastianleaf commented on esapi/views/resume.py
> +            print(hit_row)
Ok

2020-03-25 12:59 UTC, Bastianleaf commented on esapi/views/resume.py
> +            print row
Ok

2020-03-25 13:00 UTC, Bastianleaf commented on esapi/views/resume.py
> +                    print(keys[key])
Ok

2020-03-25 13:00 UTC, Bastianleaf commented on esapi/views/resume.py
>          return JsonResponse(response)
Ok

2020-03-25 13:13 UTC, Bastianleaf commented on esapi/tests/testBaseIndex.py
> +        print(result)
Ok

2020-03-25 13:13 UTC, Bastianleaf commented on esapi/views/resume.py
> +        'name': 'N° de validaciones en décimo paradero de bus con más validaciones', 'chartName': '', 'order': 97},
Ok

2020-03-25 13:19 UTC, Bastianleaf commented on esapi/tests/testShapeView.py
> +        # self.assertDictEqual(answer, ESQueryRouteParameterDoesNotExist().get_status_response())
Ok

2020-03-25 13:20 UTC, Bastianleaf commented on esapi/tests/testShapeView.py
> +        # self.assertDictEqual(answer, ESQueryDateParametersDoesNotExist().get_status_response())
Ok

2020-03-25 13:20 UTC, Bastianleaf commented on esapi/tests/testResumeView.py
> +        # self.assertJSONEqual(response.content, expected)
Ok

2020-03-25 13:26 UTC, Bastianleaf commented on esapi/errors.py
> +        super(ESQueryDateRangeParametersDoesNotExist, self).__init__(403, message)
Ok, lo regreso a 402.

2020-03-25 13:33 UTC, Bastianleaf commented on esapi/tests/testProfileView.py
> +    #     self.assertJSONEqual(response.content, expected)
Ok

2020-03-25 13:47 UTC, Bastianleaf commented on esapi/tests/testBaseIndex.py
>  class IndexNameTest(TestCase):
OK perfecto, utilizaré la alternativa del override.

2020-03-25 13:50 UTC, felipinbombin approved these changes

2020-03-25 13:52 UTC, merged