feature-settings-readme-improvement
SmartcitySantiagoChile/fondefVizServer pull request #3
Opened 2020-01-07 13:47 UTC by Bastianleaf

Se crea README.md, el cuál contiene una guía de instalación, configuración y ejecución del proyecto.
Se modifica el archivo settings.py, separando las apps de Django con fin de tener una estructura más organizada.

2020-01-07 18:17 UTC, felipinbombin requested changes

2020-01-07 18:17 UTC, felipinbombin commented on README.md
> + y Redis.
hay un salto de línea innecesario

2020-01-07 18:17 UTC, felipinbombin commented on README.md
> +#####Dependencias
Cambiar por `Dependencias python`. Además explicar que se deben instalar sobre un entorno virtual, para referencia de esto ver esta documentación https://github.com/SmartcitySantiagoChile/S3FileUploader

2020-01-07 18:17 UTC, felipinbombin commented on README.md
> +Para poder utilizar bower, se requiere tener instalado el gestor de paquetes npm:
eliminar coma

2020-01-07 18:17 UTC, felipinbombin commented on README.md
> +    URL_PREFIX=''
mover esta variable a la sección "Configuraciones generales de Django"

2020-01-07 18:17 UTC, felipinbombin commented on README.md
> +    DOWNLOAD_PATH=
mover esta variable a la sección "Configuraciones generales de Django"

2020-01-07 18:17 UTC, felipinbombin commented on README.md
> +    #Configuraciones de GPS
Cambiar nombre de sección a `Configuración de buckets para almacenamiento de datos en S3`

2020-01-07 18:17 UTC, felipinbombin commented on README.md
> +* URL_PREFIX:
mover a la configuración general de django y agregar la definición `usado por django_js_reverse para construir las urls usadas en los archivos js, por defecto es un string vacío`

2020-01-07 18:17 UTC, felipinbombin commented on README.md
> +* DOWNLOAD_PATH: path de descarga para archivos manipulados por redis
mover a la configuración general de django, modificar la definición, no son manipulados por Redis sino que por los workers

2020-01-07 18:17 UTC, felipinbombin commented on README.md
> +#####Configuraciones de GPS
Cambiar el título a `Configuración de buckets para almacenamiento de datos en S3`

2020-01-07 18:17 UTC, felipinbombin commented on README.md
> +    $ python manage.py migrate
esto se debe llamar antes del comando `loaddata`, esta sección crea las tablas en la base de datos y el comando `loaddata` inserta datos en esas tablas. Además, el comando `makemigrations` no es necesario, quitar.

2020-01-07 18:17 UTC, felipinbombin commented on README.md
> +Se debe crear un super usuario para poder acceder a la aplicación, esto se hace por medio del siguiente comando:
agregar: ... acceder a la aplicación `desde la interfaz web`, ...

2020-01-07 18:17 UTC, felipinbombin commented on README.md
> +Se debe ejecutar django_js_reverse para el manejo de las urls :
agregar: ... para el manejo de las urls `en los archivos js`

2020-01-07 18:17 UTC, felipinbombin commented on README.md
> +los rqworkers, los cuales son los que ejecutaran los procesos segundo plano:
quitar salto de línea, falta acento en `ejecutarán`. Además, agregar: `... ejecutarán los procesos en segundo plano`

2020-01-07 18:17 UTC, felipinbombin commented on fondefVizServer/settings.py
> +
quitar espacio

2020-01-08 13:03 UTC, Bastianleaf commented
Se corrigieron los cambios solicitados.

2020-01-08 13:33 UTC, felipinbombin commented on README.md
> +comandos:
Está en plural

2020-01-15 09:34 UTC, merged