Feature/consistency checker
SmartcitySantiagoChile/fondefVizServer pull request #36
Opened 2020-04-22 20:05 UTC by Bastianleaf

2020-04-22 21:02 UTC, felipinbombin requested changes

2020-04-22 21:02 UTC, felipinbombin commented on consistencychecker/management/commands/buildconsistencymetrics.py
> +        date_dict = defaultdict()
Es más simple si defines la estructura que esperas cuando el índice no existe en este punto, queda genérico a la lista de índices, lo mismo más abajo.
```
date_dict = defaultdict(lambda: {key: {'lines': 0, 'docNumber': 0} for key in keys_list})
```

2020-04-22 21:02 UTC, felipinbombin commented on consistencychecker/management/commands/buildconsistencymetrics.py
> +                    date_dict[date] = date_info
dejar solo la línea `date_dict[date].update(date_info)`

2020-04-22 21:02 UTC, felipinbombin commented on consistencychecker/management/commands/buildconsistencymetrics.py
> +                    date_dict[date].update({key: {"lines": 0, "docNumber": 0}})
ya no es necesario esta parte, quitar

2020-04-22 21:02 UTC, felipinbombin commented on consistencychecker/management/commands/buildconsistencymetrics.py
> +                                       general_file=date_dict[date]['general']['docNumber'])
esto se puede generalizar para futuras inserciones, de la siguiente forma:
```
params = dict(date=datetime.strptime(date, '%Y-%m-%d'))
for index_name in keys_list:
    aux = dict()
    aux['{0}_file'.format(index_name)] = date_dict[date][index_name]['lines']
    aux['{0}_index'.format(index_name)] = date_dict[date][index_name]['docNumber']
    params.update(aux)

Consistency.objects.create(**params)
```

entonces, si se agrega un nuevo índice se debe agregar a keys_list y al modelo y listo, no hay que tocar el código.

2020-04-22 21:02 UTC, felipinbombin commented on consistencychecker/templates/consistencychecker/consistency.html
> +        <link href="{% static gentelella_static|add:"datatables.net-scroller-bs/css/scroller.bootstrap.min.css" %}"
está duplicado

2020-04-22 21:02 UTC, felipinbombin commented on consistencychecker/static/consistencychecker/js/loadConsistency.js
> +                },
esto se puede generalizar a una lista de índices y luego para cada uno de esos ítemes se crea un elemento de esta lista, mejorar

2020-04-22 21:02 UTC, felipinbombin commented on consistencychecker/static/consistencychecker/js/loadConsistency.js
> +            sum_dif += (data.general_file - data.general_index);
también se puede generalizar

2020-04-22 21:02 UTC, felipinbombin commented on consistencychecker/templates/consistencychecker/consistency.html
> +        <script src="{% static gentelella_static|add:"iCheck/icheck.min.js" %}"></script>
esto no se usa

2020-04-22 21:02 UTC, felipinbombin commented on consistencychecker/templates/consistencychecker/consistency.html
> +        <link href="{% static gentelella_static|add:"iCheck/skins/flat/green.css" %}" rel="stylesheet">
esto no se usa

2020-04-22 21:02 UTC, felipinbombin commented on consistencychecker/tests.py
> +        self.check_http_response(self.client, 'consistencychecker:getConsistencyData', 200)
acá faltaron test relacionados al comando creado, eso se puede hacer usando la función `call_command` y revisando el output. Un ejemplo: https://docs.djangoproject.com/en/3.0/topics/testing/tools/#management-commands

2020-04-22 21:25 UTC, Bastianleaf commented on consistencychecker/management/commands/buildconsistencymetrics.py
> +        date_dict = defaultdict()
Ok

2020-04-22 21:25 UTC, Bastianleaf commented on consistencychecker/management/commands/buildconsistencymetrics.py
> +                    date_dict[date] = date_info
Ok

2020-04-22 21:25 UTC, Bastianleaf commented on consistencychecker/management/commands/buildconsistencymetrics.py
> +                    date_dict[date].update({key: {"lines": 0, "docNumber": 0}})
Ok

2020-04-22 21:26 UTC, Bastianleaf commented on consistencychecker/management/commands/buildconsistencymetrics.py
> +                                       general_file=date_dict[date]['general']['docNumber'])
Ok

2020-04-22 21:27 UTC, Bastianleaf commented on consistencychecker/templates/consistencychecker/consistency.html
> +        <link href="{% static gentelella_static|add:"datatables.net-scroller-bs/css/scroller.bootstrap.min.css" %}"
Ok

2020-04-22 21:28 UTC, Bastianleaf commented on consistencychecker/templates/consistencychecker/consistency.html
> +        <link href="{% static gentelella_static|add:"iCheck/skins/flat/green.css" %}" rel="stylesheet">
Ok

2020-04-22 21:54 UTC, Bastianleaf commented on consistencychecker/static/consistencychecker/js/loadConsistency.js
> +                },
Ok

2020-04-24 04:07 UTC, felipinbombin requested changes

2020-04-24 04:07 UTC, felipinbombin commented on consistencychecker/templates/consistencychecker/consistency.html
> +        <link href="{% static gentelella_static|add:"iCheck/skins/flat/green.css" %}" rel="stylesheet">
falta quitar icheck

2020-04-27 13:18 UTC, merged