Feature/tests rqworkers
SmartcitySantiagoChile/fondefVizServer pull request #37
Opened 2020-04-28 14:30 UTC by Bastianleaf

2020-04-28 17:57 UTC, felipinbombin requested changes

2020-04-28 17:57 UTC, felipinbombin commented on rqworkers/tests/testTasks.py
> +            name = "".join(file_path.split("/")[1])
esto es lo mismo que: `name = file_path.split("/")[1]` el join sobra

2020-04-28 17:57 UTC, felipinbombin commented on rqworkers/tests/testTasks.py
> +        upload_file.return_value = mock.Mock()
esta fila no es necesaria, quitar

2020-04-28 17:57 UTC, felipinbombin commented on rqworkers/tests/testTasks.py
> +        uploader_job_execution.side_effect = [UploaderJobExecution.DoesNotExist, uploader_job_in_dbb]
el nombre de la variable tiene un `b` al final extra, quitar

2020-04-28 17:57 UTC, felipinbombin commented on rqworkers/tests/testTasks.py
> +        upload_file.return_value = mock.Mock()
no es necesario, quitar

2020-04-28 17:57 UTC, felipinbombin commented on rqworkers/tests/testTasks.py
> +        traceback.return_value = mock.MagicMock()
no es necesaria esta asignación, para probar que se hizo se puede llamar al método `traceback.assert_called_once()`

2020-04-28 17:57 UTC, felipinbombin commented on rqworkers/tests/testTasks.py
> +        traceback.return_value = mock.MagicMock()
no es necesario, quitar

2020-04-28 17:57 UTC, felipinbombin commented on rqworkers/tests/testTasks.py
> +        download_file.return_value = mock.Mock()
no es necesario, quitar

2020-04-28 17:57 UTC, felipinbombin commented on rqworkers/tests/testTasks.py
> +        download_file.return_value = mock.Mock()
no es necesario, quitar

2020-04-28 17:57 UTC, felipinbombin commented on rqworkers/tests/testTasks.py
> +        download_file.return_value = mock.Mock()
no es necesario, quitar

2020-04-28 17:57 UTC, felipinbombin commented on rqworkers/tests/testTasks.py
> +        traceback.return_value = mock.MagicMock()
no es necesario, quitar

2020-04-28 17:57 UTC, felipinbombin commented on rqworkers/tests/testTasks.py
> +        traceback.return_value = mock.MagicMock()
no es necesario, quitar

2020-04-29 19:10 UTC, Bastianleaf commented on rqworkers/tests/testTasks.py
> +            name = "".join(file_path.split("/")[1])
Ok

2020-04-29 19:10 UTC, Bastianleaf commented on rqworkers/tests/testTasks.py
> +        upload_file.return_value = mock.Mock()
Ok

2020-04-29 19:17 UTC, Bastianleaf commented on rqworkers/tests/testTasks.py
> +        uploader_job_execution.side_effect = [UploaderJobExecution.DoesNotExist, uploader_job_in_dbb]
Ok

2020-04-29 19:18 UTC, Bastianleaf commented on rqworkers/tests/testTasks.py
> +        upload_file.return_value = mock.Mock()
Ok

2020-04-29 19:27 UTC, Bastianleaf commented on rqworkers/tests/testTasks.py
> +        download_file.return_value = mock.Mock()
Ok

2020-04-29 19:27 UTC, Bastianleaf commented on rqworkers/tests/testTasks.py
> +        download_file.return_value = mock.Mock()
Ok

2020-04-29 19:27 UTC, Bastianleaf commented on rqworkers/tests/testTasks.py
> +        download_file.return_value = mock.Mock()
Ok

2020-04-29 19:27 UTC, Bastianleaf commented on rqworkers/tests/testTasks.py
> +        traceback.return_value = mock.MagicMock()
Ok

2020-04-29 19:27 UTC, Bastianleaf commented on rqworkers/tests/testTasks.py
> +        traceback.return_value = mock.MagicMock()
Ok

2020-04-29 21:46 UTC, Bastianleaf commented on rqworkers/tests/testTasks.py
> +        traceback.return_value = mock.MagicMock()
Ok

2020-04-30 05:26 UTC, felipinbombin approved these changes

2020-04-30 05:27 UTC, merged