Feature/consistency downloader
SmartcitySantiagoChile/fondefVizServer pull request #40
Opened 2020-05-04 20:19 UTC by Bastianleaf

2020-05-04 22:18 UTC, felipinbombin requested changes

2020-05-04 22:18 UTC, felipinbombin commented on consistencychecker/templates/consistencychecker/consistency.html
> +        <script src="{% static gentelella_static|add:"jquery-sparkline/dist/jquery.sparkline.min.js" %}"></script>
esta librería es para hacer gráficos en las celdas, entiendo que no se usa acá, quitar

2020-05-04 22:18 UTC, felipinbombin commented on consistencychecker/templates/consistencychecker/consistency.html
> +        <script src="{% static gentelella_static|add:"datatables.net-buttons/js/buttons.html5.min.js" %}"></script>
están duplicadas estas líneas, quitar

2020-05-04 22:18 UTC, felipinbombin commented on consistencychecker/static/consistencychecker/js/loadConsistency.js
> +                    }
esto es para filtrar las columnas del excel, como se están poniendo todas no es necesario, quitar

2020-05-04 22:28 UTC, Bastianleaf commented on consistencychecker/templates/consistencychecker/consistency.html
> +        <script src="{% static gentelella_static|add:"jquery-sparkline/dist/jquery.sparkline.min.js" %}"></script>
Ok

2020-05-04 22:28 UTC, Bastianleaf commented on consistencychecker/templates/consistencychecker/consistency.html
> +        <script src="{% static gentelella_static|add:"datatables.net-buttons/js/buttons.html5.min.js" %}"></script>
Ok

2020-05-04 22:32 UTC, Bastianleaf commented on consistencychecker/static/consistencychecker/js/loadConsistency.js
> +                    }
Ok

2020-05-05 14:22 UTC, felipinbombin approved these changes

2020-05-05 14:22 UTC, merged