Feature/improve datamanager data view
SmartcitySantiagoChile/fondefVizServer pull request #66
Opened 2020-07-14 15:45 UTC by Bastianleaf

- A la url /admin/datamanager/data/ se le agrega la opción de recibir el parametro filters[] por GET con los índices de elasticsearch.
- Al método _get_file_list se le agrega el filtro para consultar solo los archivos perteneciente a los índices correspondientes.
- Al método get_document_number_by_file_from_elasticsearch se le agrega un diccionario para búscar solo en los índices filtrados.

2020-07-15 16:55 UTC, felipinbombin commented on datamanager/views.py
> -            'routeDictFiles': FileManager().get_file_list()
veo que recuperas una lista de filtros pero la rama no modifica ningún javascript, esos datos ya se enviaban en la request?

2020-07-21 02:33 UTC, felipinbombin requested changes

2020-07-21 02:33 UTC, felipinbombin commented on datamanager/templates/datamanager/loadManager.html
> +    ></script>
pienso que esto se debería llevar al view que usa el template, es decir asignar el valor de la lista en ella y acá renderizar la variable (el template solo sabe que debe mostrar la variable de una forma) usando https://docs.djangoproject.com/en/3.0/ref/templates/builtins/#json-script para luego rescatar el valor en el javascript. La idea es que la lógica se mantenga en el view

2020-07-21 13:58 UTC, Bastianleaf commented on datamanager/templates/datamanager/loadManager.html
> +    ></script>
Tienes razón, lo haré de esa forma.

2020-07-21 18:01 UTC, felipinbombin requested changes

2020-07-21 18:01 UTC, felipinbombin commented on datamanager/views.py
> -            'routeDictFiles': FileManager().get_file_list()
esta lista también se debería filtrar, no los necesito todos, solo los que voy a mostrar

2020-07-21 18:20 UTC, Bastianleaf commented on datamanager/views.py
> -            'routeDictFiles': FileManager().get_file_list()
¿A qué te refieres con esto? la linea 212 justamente recibe solo los índices que voy a mostrar

2020-07-23 17:16 UTC, felipinbombin approved these changes

2020-07-23 17:16 UTC, felipinbombin commented on datamanager/views.py
> -            'routeDictFiles': FileManager().get_file_list()
tienes razón, olvida esto 🤦

2020-07-23 17:17 UTC, merged