Feature/docker
SmartcitySantiagoChile/fondefVizServer pull request #68
Opened 2020-07-24 04:31 UTC by Bastianleaf

Se agregan archivos de configuración para docker.

2020-07-24 15:44 UTC, felipinbombin requested changes
falta corregir la comunicación con elasticsearch del docker-compose y unos detalles.

Otra cosa es que pienso que no está es la configuración del sub módulo  en el proceso de build, si yo descargo el proyecto de github debo hacer eso de poder hacer el build sino va fallar

2020-07-24 15:44 UTC, felipinbombin commented on docker/docker-compose.yml
> +      - cache_network
este no es necesario para correr el servicio, quitar. La idea de tener el comando `test` es que se puedan correr las pruebas en el contenedor, sin el docker-compose, de esta forma: 
```
docker build -f docker\Dockerfile -t adatrap-server:latest .
docker run --rm --name=adatrap-server adatrap-server:latest test
```

2020-07-24 15:44 UTC, felipinbombin commented on docker/docker-compose.yml
> +      - 9200:9200
creo que no es necesario publicar el puerto de elasticsearch puesto que no lo consultaremos de afuera (desde la máquina host), dado esto, sería bueno crear una imagen que contenga a cerebro, que ese sea público, así podemos mirar lo que pasa en elasticsearch a través de una interfaz

2020-07-24 15:44 UTC, felipinbombin commented on docker/docker-compose.yml
> +      - cache_network
creo que esta dependencia a la red del caché no es necesaria, probar

2020-07-24 15:44 UTC, felipinbombin commented on docker/docker_env
> +ELASTICSEARCH_HOST=172.17.74.243
pienso que esto no está bien, no debería funcionar como está porque no se está conectando al host `es`, se debe reemplazar la ip por `es`, el contenedor de elasticsearch

2020-07-24 15:44 UTC, felipinbombin commented on docker/entrypoint.sh
> +    python manage.py collectstatic_js_reverse
este debe ser llamado antes del collectstatic

2020-07-24 15:44 UTC, felipinbombin commented on docker/entrypoint.sh
> +    python manage.py collectstatic_js_reverse
el entrypoint debería también llamar al comando createindexes para crear los índices en el contenedor `es`, creo que probaste todo con el server de desarrollo de adatrap y por eso se te pasó toda esta configuración

2020-07-24 15:47 UTC, felipinbombin commented on docker/docker-compose.yml
> +      - cache_network
agregar esto al readme, una sección "ejecutar test"

2020-07-24 17:08 UTC, Bastianleaf commented on docker/docker-compose.yml
> +      - cache_network
Entiendo, lo haré de esa foorma entonces.

2020-07-24 17:08 UTC, Bastianleaf commented on docker/docker-compose.yml
> +      - 9200:9200
Ok, agregaré a cerebro.

2020-07-24 17:08 UTC, Bastianleaf commented on docker/docker_env
> +ELASTICSEARCH_HOST=172.17.74.243
Ok

2020-07-24 17:13 UTC, Bastianleaf commented on docker/entrypoint.sh
> +    python manage.py collectstatic_js_reverse
Ok, efectivamente, al final lo probé con el server de desarrollo para probar las funcionalidades con datos. Haré los cambios necesarios para que funcione correctamente con el contenedor es.

2020-07-24 17:13 UTC, Bastianleaf commented on docker/docker-compose.yml
> +      - cache_network
Ok, probaré.

2020-07-30 23:35 UTC, felipinbombin approved these changes

2020-08-04 18:36 UTC, felipinbombin requested changes

2020-08-04 18:36 UTC, felipinbombin commented on docker/docker-compose-test.yml
> +      - postgres_fondefdev_data:/var/lib/postgresql/data/
quitar el volumes, acá no se justifica mantener los datos

2020-08-04 20:07 UTC, Bastianleaf commented on docker/docker-compose-test.yml
> +      - postgres_fondefdev_data:/var/lib/postgresql/data/
Ok

2020-08-05 19:27 UTC, felipinbombin approved these changes

2020-08-05 19:27 UTC, merged