Hotfix/opdata issues
SmartcitySantiagoChile/fondefVizServer pull request #69
Opened 2020-07-28 17:02 UTC by Bastianleaf

- Se modifica texto de error cuando no sse encuentra un código en el diccionario PO.
- Se realiza la traducción de periodos transantiago para tabla de información respecto a programa de operación.
- Se corrige error de conteo de lineas en carga de datos op.
- Se ordena de forma descendiente las fechas en programas de operación para la vista Rutas->Ficha de Servicios

2020-07-28 18:35 UTC, felipinbombin requested changes

2020-07-28 18:35 UTC, felipinbombin commented on esapi/tests/testOpDataView.py
> +                     verbosity=0)
la forma correcta de cargar un fixture en un test es usando la variable fixture de la clase, revisar esto https://docs.djangoproject.com/en/3.0/topics/testing/tools/#fixture-loading y corregir

2020-07-28 19:53 UTC, Bastianleaf commented on esapi/tests/testOpDataView.py
> +                     verbosity=0)
Ok, corregido.

2020-07-29 04:20 UTC, felipinbombin approved these changes

2020-07-29 04:20 UTC, merged