Feature/by many stop view
SmartcitySantiagoChile/fondefVizServer pull request #7
Opened 2020-01-24 18:08 UTC by Bastianleaf

2020-01-25 17:02 UTC, felipinbombin requested changes

2020-01-25 17:02 UTC, felipinbombin commented on esapi/helper/profile.py
> +                                    'dayType', 'timePeriodInStopTime', 'loadProfile', 'busStation', 'path'])
Esta parte no es necesaria porque estamos diciendo que cada documento me entregue los siguientes atributos (los escritos en la lista), sin embargo, en la línea siguiente le decimos que no queremos documentos (`es_query = es_query[:0]`). Quitar

2020-01-25 17:02 UTC, felipinbombin commented on esapi/helper/profile.py
> +        # group by userStopName
quitar este comentario, no es necesario

2020-01-25 17:02 UTC, felipinbombin commented on esapi/static/js/filterManager.js
> +        var localMultiStopFilter = window.localStorage.getItem("multiStopFilter");
agregar el sufijo de la vista, si lo llegamos a usar en otras vista más adelante nos evitará un problema.

2020-01-25 17:02 UTC, felipinbombin commented on esapi/urls.py
> +    url(r'^profile/BoardingAndAlightingAverageByStops/$', login_required(BoardingAndAlightingAverageByStops.as_view()),
las urls comienzan con minúscula, usar `boarding...`

2020-01-25 17:02 UTC, felipinbombin commented on esapi/urls.py
> +        name='BoardingAndAlightingAverageByStops'),
el nombre comienza con minúscula

2020-01-25 17:02 UTC, felipinbombin commented on esapi/views/profile.py
> +                ExporterManager(es_query).export_data(csv_helper.PROFILE_BY_STOP_DATA, request.user)
la parte de `csv_helper.PROFILE_BY_STOP_DATA` pienso que no va a funcionar. Inicia los workers y prueba realizando la exportación. En este caso se usa el índice profile por lo que son esos datos los que se deberían exportar. Entonces, deberíamos usar la misma variable que usa la vista del perfil de carga.

2020-01-25 17:02 UTC, felipinbombin commented on profile/templates/profile/byManyStops.html
> +
dejar una línea de separación

2020-01-25 17:02 UTC, felipinbombin commented on profile/static/profile/js/byManyStops.js
> +            urlFilterData: Urls["esapi:BoardingAndAlightingAverageByStops"](),
poner minúscula la primera letra `esapi:boarding...`

2020-01-25 17:02 UTC, felipinbombin commented on profile/static/profile/js/byManyStops.js
> +    }
si no se usa, quitar

2020-01-25 17:02 UTC, felipinbombin commented on profile/static/profile/js/byManyStops.js
> +
quitar espacio

2020-01-25 17:02 UTC, felipinbombin commented on profile/static/profile/js/byManyStops.js
> +
dejar un espacio

2020-01-25 17:02 UTC, felipinbombin commented on profile/static/profile/js/byManyStops.js
> +        this.calculateAverage = function () {
¿por qué sigue siendo necesario correr esto si ya se calculan los promedios en elasticsearch? 🤔

2020-01-27 12:23 UTC, Bastianleaf commented on esapi/helper/profile.py
> +                                    'dayType', 'timePeriodInStopTime', 'loadProfile', 'busStation', 'path'])
Ok, lo borraré.

2020-01-27 12:23 UTC, Bastianleaf commented on esapi/helper/profile.py
> +        # group by userStopName
Ok

2020-01-27 12:24 UTC, Bastianleaf commented on esapi/static/js/filterManager.js
> +        var localMultiStopFilter = window.localStorage.getItem("multiStopFilter");
Ok

2020-01-27 12:25 UTC, Bastianleaf commented on esapi/urls.py
> +    url(r'^profile/BoardingAndAlightingAverageByStops/$', login_required(BoardingAndAlightingAverageByStops.as_view()),
Ok

2020-01-27 12:26 UTC, Bastianleaf commented on profile/static/profile/js/byManyStops.js
> +    }
Ok

2020-01-27 12:27 UTC, Bastianleaf commented on profile/static/profile/js/byManyStops.js
> +
Ok

2020-01-27 12:27 UTC, Bastianleaf commented on profile/static/profile/js/byManyStops.js
> +
Ok

2020-01-27 13:07 UTC, Bastianleaf commented on profile/templates/profile/byManyStops.html
> +
Ok

2020-01-27 14:24 UTC, Bastianleaf commented on esapi/views/profile.py
> +                ExporterManager(es_query).export_data(csv_helper.PROFILE_BY_STOP_DATA, request.user)
Conversado

2020-01-28 04:22 UTC, felipinbombin approved these changes

2020-01-28 04:22 UTC, merged