Soporte de archivos excel en carga de diccionarios OP
SmartcitySantiagoChile/fondefVizServer pull request #77
Opened 2020-09-16 17:12 UTC by Bastianleaf

Se modifica la carga de diccionarios OP para que cargue archivos excel:

- Se cambian los nombres de referencia de los templates de csvDictionary/Form a OPDictionary/Form
- Se divide en dos secciones la carga del diccionario:
   - En las localinfo/helper se encuentra la función upload_xlsx_op_dictionary que toma un archivo excel y lo agrega a la base de datos, retornando True en caso de agregar/actualizar y false si es que no se hace nada.
   - En localinfo/views se recibe el diccionario vía formulario, se llama a upload_xlsx_op_dictionary, dependiendo de la respuesta de la función, o si es que ocurre una excepción, retorna un código de status al usuario.
- Se agregan los test correspondientes.
- Se elimina toda referencia a la carga de archivos csv.
- Se agrega a requirements.txt la librería openpyxl, las principales ventajas que tiene son:
   - De las librerías más comunes usadas para leer excel en python.
   - Tiene un modo optimizado para solo lectura, este puede ser usado para leer archivos muy pesados sin ocupar mucha memoria.
   - Semántica sencilla.
- Se probó el archivo de ejemplo y se cargó exitosamente.

2020-09-17 02:39 UTC, felipinbombin requested changes

2020-09-17 02:39 UTC, felipinbombin commented on localinfo/helper.py
> +            break
¿esto es para encontrar la primera línea vacía y en ese caso salé del loop?

2020-09-17 02:39 UTC, felipinbombin commented on localinfo/helper.py
> +    wb.close()
esto se puede cerrar antes de hacer los inserts o updates, no es necesario mantenerlo abierto

2020-09-17 02:39 UTC, felipinbombin commented on localinfo/helper.py
> +        return True
esto no me convence, acá queremos mostrar el caso cuando el archivo está vacío? que entiendo sería la única situación en que se produce esto, en ese caso puedo lanzar una exception si la línea 1 es vacía (la que viene después del header), quien use esta función debería hacerse cargo de atrapar la exception y mostrar un mensaje al usuario, esta forma me permite agregar más exceptions a la función y quien las use puede lanzar otros mensajes, con la forma True o False no puedo, me limita a una condición, creo que la función no debería retornar esto, quizás podría retornar el número de registros que se actualizan y que se crean, con el eso quien llamó a la función puede lanzar un mensaje al uusuario indicando "Se han insertado XX registros y actualizado XX registros". Mejorar

2020-09-17 02:39 UTC, felipinbombin commented on localinfo/views.py
> +                    return JsonResponse(data={"error": "El archivo tiene problemas en su formato."}, status=400)
esto debería cambiar a un try except según lo comentado el comentario anterior

2020-09-17 13:40 UTC, Bastianleaf commented on localinfo/helper.py
> +    wb.close()
Ok

2020-09-17 13:40 UTC, Bastianleaf commented on localinfo/helper.py
> +            break
Efectivamente, no encontré en la librería una forma directa de iterar hasta que sea vacío ya que la otra opción es especificar cuantas lineas se iterarán.

2020-09-17 13:41 UTC, Bastianleaf commented on localinfo/helper.py
> +        return True
Correcto, lo dejaré de la forma que indique cuantas se han insertado y actualizado.

2020-09-17 13:41 UTC, Bastianleaf commented on localinfo/views.py
> +                    return JsonResponse(data={"error": "El archivo tiene problemas en su formato."}, status=400)
Ok

2020-09-23 03:33 UTC, felipinbombin approved these changes

2020-09-23 03:33 UTC, felipinbombin commented on localinfo/helper.py
> +                op_dict_obj = OPDictionary.objects.get(auth_route_code=auth_route_code)
esta condición debería incluir además al route_type, entonces quedaría como `auth_route_code=auth_route_code, route_type=route_type`. Esto es necesario puesto que pueden haber distintos route_type con el mismo aut_route_code.

2020-09-23 03:33 UTC, merged