Modificaciones a ficha de servicios
SmartcitySantiagoChile/fondefVizServer pull request #82
Opened 2020-10-29 17:34 UTC by Bastianleaf

- Se ordena alfabéticamente los servicios de usuario.
- Se cambia de error a warning cuando no existe secuencia de parada.
- Se corrige el comportamiento de cambio de color.
- Se elimina filtro de periodos y botón a ficha de servicios.
- Se agrega nuevo botón a ficha de servicios.
- Se modifica la ficha de servicios:
   - Se agrega barra de búsqueda (operativa para fechas, rutas de usuario y rutas sonda)
   - Se agrega selector para periodo transantiago.
   - Se agregan columnas de fecha, servicio usuario y servicio sonda.
- Se crea un nuevo bloque de información para cuando se cargue la ficha de servicios y no se encuentre información sobre alguna ruta.

2020-10-29 20:42 UTC, felipinbombin requested changes
El filtro del período Transantiago debería permitir elegir uno o más, está en la tarjeta (penúltimo punto). 

Otra mejora que veo hay que realizar es quitar el tramo horario que aparece en el campo timePeriod, no la veo necesaria si aparecen en las columnas Inicio y Fin. Entonces en el selector deberían aparecer sin hora y en la columna igual. Me queda la duda de si se usa en otra parte con ese formato.

Otra cosa, si selecciono dos filas con el mismo servicio en la tabla se muestra dos veces, debería ser una.

En el botón que tiene el icono de información usaría el icono fa-bus y agregaría un texto a la derecha de este "Ver información operacional".

si tengo un paradero oculto, y cambio el servicio, el botón sigue en el estado de paraderos ocultos pero los muestra. Mismo comportamiento con la ruta.

El último punto de la tarjeta me sigue ocurriendo:
"si trato de cargar un servicio desde otro programa de operación distinto al 2020-06-27 se cae con el error "Cannot read property 'T461 00R' of undefined". El código es un ejemplo, dependiendo de la situación podría ser otro."

2020-10-30 23:35 UTC, Bastianleaf commented
> Otra mejora que veo hay que realizar es quitar el tramo horario que aparece en el campo timePeriod, no la veo necesaria si aparecen en las columnas Inicio y Fin. Entonces en el selector deberían aparecer sin hora y en la columna igual. Me queda la duda de si se usa en otra parte con ese formato.

Respecto a esto estoy de acuerdo conque eliminar el paréntesis en la columna, no obstante, considero que sería contraproducente eliminar el paréntesis en el selector ya que existen periodos transantiago con el mismo nombre y distinto horario inicial y final, por ejemplo, pre nocturno, el cuál puede ser 00:00:00 - 00:59:59 o 23:00:00 - 23:59:59

2020-11-02 02:16 UTC, felipinbombin commented
> > Otra mejora que veo hay que realizar es quitar el tramo horario que aparece en el campo timePeriod, no la veo necesaria si aparecen en las columnas Inicio y Fin. Entonces en el selector deberían aparecer sin hora y en la columna igual. Me queda la duda de si se usa en otra parte con ese formato.
> 
> Respecto a esto estoy de acuerdo conque eliminar el paréntesis en la columna, no obstante, considero que sería contraproducente eliminar el paréntesis en el selector ya que existen periodos transantiago con el mismo nombre y distinto horario inicial y final, por ejemplo, pre nocturno, el cuál puede ser 00:00:00 - 00:59:59 o 23:00:00 - 23:59:59

Eso tiene sentido si es que el filtro del selector fuera por el identificador del período, pero en este caso es por el nombre, entonces ese nombre puede tener distintos horarios según el PO, por ejemplo, el usuario puede decir "quiero filtrar por el nombre de período 'Punta Manaña'", al indicar eso (y si tiene seleccionado más de un PO), obtendría: 
```
fila1 |  Punta Mañana | 06:00 | 09:00
fila2 |  Punta Mañana | 06:30 | 09:30
```
Entonces es la fila la que entrega la diferencia de hora, lo importante es que el selector permita seleccionar esas filas ¿se entiende?

2020-11-02 19:38 UTC, Bastianleaf commented
> > > Otra mejora que veo hay que realizar es quitar el tramo horario que aparece en el campo timePeriod, no la veo necesaria si aparecen en las columnas Inicio y Fin. Entonces en el selector deberían aparecer sin hora y en la columna igual. Me queda la duda de si se usa en otra parte con ese formato.
> > 
> > 
> > Respecto a esto estoy de acuerdo conque eliminar el paréntesis en la columna, no obstante, considero que sería contraproducente eliminar el paréntesis en el selector ya que existen periodos transantiago con el mismo nombre y distinto horario inicial y final, por ejemplo, pre nocturno, el cuál puede ser 00:00:00 - 00:59:59 o 23:00:00 - 23:59:59
> 
> Eso tiene sentido si es que el filtro del selector fuera por el identificador del período, pero en este caso es por el nombre, entonces ese nombre puede tener distintos horarios según el PO, por ejemplo, el usuario puede decir "quiero filtrar por el nombre de período 'Punta Manaña'", al indicar eso (y si tiene seleccionado más de un PO), obtendría:
> 
> ```
> fila1 |  Punta Mañana | 06:00 | 09:00
> fila2 |  Punta Mañana | 06:30 | 09:30
> ```
> 
> Entonces es la fila la que entrega la diferencia de hora, lo importante es que el selector permita seleccionar esas filas ¿se entiende?

Si, totalmente, ahora me queda claro.

2020-11-02 21:38 UTC, Bastianleaf commented
> El filtro del período Transantiago debería permitir elegir uno o más, está en la tarjeta (penúltimo punto).
> 
> Otra mejora que veo hay que realizar es quitar el tramo horario que aparece en el campo timePeriod, no la veo necesaria si aparecen en las columnas Inicio y Fin. Entonces en el selector deberían aparecer sin hora y en la columna igual. Me queda la duda de si se usa en otra parte con ese formato.
> 
> Otra cosa, si selecciono dos filas con el mismo servicio en la tabla se muestra dos veces, debería ser una.
> 
> En el botón que tiene el icono de información usaría el icono fa-bus y agregaría un texto a la derecha de este "Ver información operacional".
> 
> si tengo un paradero oculto, y cambio el servicio, el botón sigue en el estado de paraderos ocultos pero los muestra. Mismo comportamiento con la ruta.
> 
> El último punto de la tarjeta me sigue ocurriendo:
> "si trato de cargar un servicio desde otro programa de operación distinto al 2020-06-27 se cae con el error "Cannot read property 'T461 00R' of undefined". El código es un ejemplo, dependiendo de la situación podría ser otro."

Ya se implementaron todos los cambios.

2020-11-03 03:45 UTC, felipinbombin reviewed
¿por qué se ve distinto el selector? y el font del botón "ver información operacional"? deberían ser iguales
![image](https://user-images.githubusercontent.com/2617940/97947869-76667900-1d6d-11eb-98c8-b17704913205.png)

Cuando agrego la primera fila, el po y el servicio aparecen seleccionados pero el selector "servicio sonda" aparece vacío a pesar de tener datos el servicio (si me cambio a otro servicio y luego vuelvo al anterior aparecen los datos). Puede estar relacionado a este error:

![image](https://user-images.githubusercontent.com/2617940/97947996-d3fac580-1d6d-11eb-8eb8-4809060ee400.png)

2020-11-03 18:48 UTC, Bastianleaf commented
> ¿por qué se ve distinto el selector? y el font del botón "ver información operacional"? deberían ser iguales
> ![image](https://user-images.githubusercontent.com/2617940/97947869-76667900-1d6d-11eb-98c8-b17704913205.png)
> 
> Cuando agrego la primera fila, el po y el servicio aparecen seleccionados pero el selector "servicio sonda" aparece vacío a pesar de tener datos el servicio (si me cambio a otro servicio y luego vuelvo al anterior aparecen los datos). Puede estar relacionado a este error:
> 
> ![image](https://user-images.githubusercontent.com/2617940/97947996-d3fac580-1d6d-11eb-8eb8-4809060ee400.png)

Corregido

2020-11-06 17:26 UTC, felipinbombin approved these changes

2020-11-06 17:26 UTC, merged