Feature/add evasion to profile visualizations
SmartcitySantiagoChile/fondefVizServer pull request #91
Opened 2021-04-05 19:15 UTC by Bastianleaf

Cambios en servidor:
- A dataDownloader/csvhelper/helper.py se le agrega información sobre nuevas columnas y se modifican los respectivos tests.
- A esapi/helper/profile.py, método  se le agregan las nuevas columnas a la consulta junto a respectivos tests.

Cambios en cliente:
- A profile/templates/profile/byExpedition.html se le agregan dependencias para switch.
- A profile/static/profile/js/byExpedition.js se le agrega nueva información de columnas.

2021-04-07 14:25 UTC, felipinbombin requested changes

2021-04-07 14:25 UTC, felipinbombin commented on esapi/helper/profile.py
> +            metric('boardingWithAlighting', 'avg', field='boardingWithAlighting')
este campo debe devolver la suma, cambiar `avg` por `sum`

2021-04-07 14:25 UTC, felipinbombin commented on esapi/helper/profile.py
> +            metric('boardingWithAlighting', 'avg', field='boardingWithAlighting')
este campo debe devolver la suma, cambiar `avg` por `sum`

2021-04-07 14:25 UTC, felipinbombin commented on esapi/tests/testProfileIndex.py
> +                                                'boardingWithAlighting': {'avg': {'field': 'boardingWithAlighting'}}}}},
reemplazar `avg` por `sum` para boardingWithAlighting

2021-04-07 14:25 UTC, felipinbombin commented on esapi/views/profile.py
> +                raise ESQueryResultEmpty()
pienso que este desplazamiento no es correcto, debería quedar como estaba

2021-04-07 14:25 UTC, felipinbombin commented on profile/templates/profile/byExpedition.html
> +        rel="stylesheet">
estas líneas son necesarias?

2021-04-07 14:25 UTC, felipinbombin commented on profile/templates/profile/byExpedition.html
> +        {# switchery: pretty checkboxes #}
estas líneas son necesarias?

2021-04-08 20:19 UTC, Bastianleaf commented on esapi/helper/profile.py
> +            metric('boardingWithAlighting', 'avg', field='boardingWithAlighting')
Ok

2021-04-08 20:20 UTC, Bastianleaf commented on esapi/helper/profile.py
> +            metric('boardingWithAlighting', 'avg', field='boardingWithAlighting')
Ok

2021-04-08 20:20 UTC, Bastianleaf commented on esapi/tests/testProfileIndex.py
> +                                                'boardingWithAlighting': {'avg': {'field': 'boardingWithAlighting'}}}}},
Ok

2021-04-08 23:17 UTC, Bastianleaf commented on esapi/views/profile.py
> +                raise ESQueryResultEmpty()
Corregido

2021-04-08 23:17 UTC, Bastianleaf commented on profile/templates/profile/byExpedition.html
> +        rel="stylesheet">
Fueron quitadas

2021-04-08 23:17 UTC, Bastianleaf commented on profile/templates/profile/byExpedition.html
> +        {# switchery: pretty checkboxes #}
Fueron quitadas

2021-04-09 17:57 UTC, felipinbombin approved these changes

2021-04-09 17:57 UTC, merged